version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: salestrack-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: salestrack
    ports:
      - '5432:5432'
    volumes:
      - salestrack-db-data:/var/lib/postgresql/data

volumes:
  salestrack-db-data:
